---
# This playbook deploys the necessary packages into a plain  Linux OS image and whole application stack in this site.  

- name: configure and deploy the webservers and simple web application
  hosts: web-servers
  remote_user: ubuntu
  sudo: yes

  roles:
    - common
    - base-apache
    - sinatra-passenger
    - webapp-deploy
