---
#this play creates the directories required for deploying the rack application and copies the files for the simple sinatra application
- name: Create the directories for deploying the rack application, if not present
  file: name=/var/www/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
      - simple-sinatra-app
      - simple-sinatra-app/tmp
      - simple-sinatra-app/public

- name: Copy the sinata application files and set the right permissions
  copy: src={{ item }} dest=/var/www/simple-sinatra-app owner=root group=root mode=0755
  with_items:
      - config.ru
      - helloworld.rb
